# === exchange ===
exchange:
  name: kraken
  max_concurrency: 3
  request_timeout_ms: 10000

kraken:
  http_pool_size: 50

# === trading/base ===
trading:
  mode: dry_run           # cex | onchain | auto | dry_run
  allowed_quotes: [USD, USDT, USDC, EUR]
  min_ticker_volume: 10000
  timeframes: ["1m","5m"]
  backfill:
    deep_low_tf: true        # backfill 1m/5m history for strategies
    deep_days: 30
  hft_enabled: true
  hft_symbols: ["BTC/USD","ETH/USD","SOL/USDC","BONK/USDC"]   # seed list, can expand
  exclude_symbols: ["AIBTC/USD"]   # remove noisy/synthetic pairs
<<<<<< codex/add-ct_require_sentiment-section-in-readme
  require_sentiment: false          # override with CT_REQUIRE_SENTIMENT=false to bypass
voting_enabled: false  # set true to enable strategy voting
# Example voting configuration
voting_strategies:
  strategies: []
  min_agreeing_votes: 1


# === ohlcv cache ===
ohlcv:
  storage_path: crypto_bot/data/ohlcv   # directory for persisted OHLCV data
  tail_overlap_bars: 3                  # overlap bars to avoid gaps when appending
  max_bootstrap_bars: 1000              # limit initial bootstrap to this many bars
  progress_logging: false               # include percent/ETA when data is missing
  bootstrap_timeframes: ["1m", "5m", "15m", "1h"]
  defer_timeframes: ["4h", "1d"]
  warmup_candles:            # auto-adjusts; override with CT_WARMUP_<TF> env vars
    "1m": 300    # CT_WARMUP_1M
    "5m": 300    # CT_WARMUP_5M
    "15m": 300   # CT_WARMUP_15M
    "1h": 200    # CT_WARMUP_1H
    "1d": 100    # CT_WARMUP_1D
  initial_history_candles: 600
  scan_lookback_limit: 1200

# Default on-chain universe and scanner options
onchain_symbols: ["SOL/USDC"]
  benchmark_symbols: ["XRP/USD", "SOL/USDC"]  # set [] to disable benchmarks
solana_scanner:
  enabled: true
  interval_minutes: 0.1
  max_tokens_per_scan: 50
solana_rpc: https://api.mainnet-beta.solana.com  # Custom endpoint

# === strategies and params ===
strategies:
  maker_spread:
    enabled: true
    max_spread_bp: 8              # don’t quote if spread > 8 bps
    edge_margin_bp: 3             # required extra edge beyond maker fee
    max_live_quotes: 2
    queue_timeout_ms: 1500        # cancel if sitting too long
    cancel_on_obi_flip: true

  breakout:
    enabled: true
    tf: "5m"
    donchian_len: 40
    keltner_len: 20
    bbw_pct_max: 15               # BB width in bottom 15th percentile
    volume_z_min: 1.0
    atr_mult_stop: 1.2
    atr_mult_tp: 1.2
    max_spread_bp: 10
    time_exit_bars: 12

  mean_bot:
    enabled: true
    trade_enabled: true
    tf: "1m"
    ema_len: 50
    z_entry: 2.0
    z_exit: 0.5
    adx_max: 18
    atr_stop_mult: 1.0
    max_spread_bp: 8
    time_exit_bars: 6

yamlmeme_sniper:
  min_pump_prob: 0.6  # Assessment threshold
  max_dev_hold_pct: 20
  min_liquidity_usd: 5000
  twitter_sentiment_min: 70
  helius_api_key: your_key_here  # For metadata

# === risk & sizing ===
risk:
  max_drawdown: 0.35
  stop_loss_pct: 0.01
  take_profit_pct: 0.1

# === fees ===
fees:
  kraken:
    taker_bp: 26    # example 0.26%
    maker_bp: 16    # example 0.16%

# === features ===
features:
  ml: true #set true to use ML regime models (requires SUPABASE_URL and SUPABASE_KEY; use service role key for private buckets or anon for public)
  helius: true
  pump_monitor: true
  telegram: true

# Regime model is fetched from Supabase; override fallback URL if needed
# model_fallback_url: https://example.com/xrpusd_regime_lgbm.pkl

# === telemetry / metrics ===
telemetry:
  batch_summary_secs: 60

# === data ===
data:
  market-loader:
    # Max minutes to wait for initial OHLCV bootstrap before giving up
    bootstrap_timeout_minutes: 10

timeframes: ['1m','5m']

backfill_days:
  '1m': 2
  '5m': 3

deep_backfill_days:
  '1m': 7
  '5m': 14

ohlcv_chunk_size: 20
telegram:
  token: YOUR_TELEGRAM_TOKEN
  chat_id: YOUR_CHAT_ID
  status_updates: true
  bootstrap_updates: false
  connect_timeout: 10.0
  read_timeout: 20.0
  connection_pool_size: 8

# === volatility filter ===
volatility_filter:
  max_funding_rate: 0.3
  min_atr_pct: 0.0001

# === sentiment filter ===
sentiment_filter:
  require_sentiment: false    # neutral defaults; CT_REQUIRE_SENTIMENT=false also bypasses checks
  min_fng: 20
  min_sentiment: 40
strict_cex: true   # only symbols the exchange actually lists
denylist_symbols: ['AIBTC/USD','AIBTC:USD','AIBTC/EUR','AIBTC:EUR','BTC/USD.P','ETH/USD.P']
