# === trading/base ===
trading:
  mode: dry_run           # cex | onchain | auto | dry_run
  exchange: kraken
  allowed_quotes: [USD, USDT, USDC, EUR]
  min_ticker_volume: 10000
  timeframes: ["1m","5m"]
  backfill:
    warmup_high_tf: ["1h","4h","1d"]
    deep_low_tf: true        # backfill 1m/5m history for strategies
    deep_days: 30
  hft_enabled: true
  hft_symbols: ["BTC/USD","ETH/USD","SOL/USDC","BONK/USDC"]   # seed list, can expand
  exclude_symbols: ["AIBTC/USD"]   # remove noisy/synthetic pairs

# === strategies and params ===
strategies:
  maker_spread:
    enabled: true
    max_spread_bp: 8              # don’t quote if spread > 8 bps
    edge_margin_bp: 3             # required extra edge beyond maker fee
    max_live_quotes: 2
    queue_timeout_ms: 1500        # cancel if sitting too long
    cancel_on_obi_flip: true

  breakout:
    enabled: true
    tf: "5m"
    donchian_len: 40
    keltner_len: 20
    bbw_pct_max: 15               # BB width in bottom 15th percentile
    volume_z_min: 1.0
    atr_mult_stop: 1.2
    atr_mult_tp: 1.2
    max_spread_bp: 10
    time_exit_bars: 12

  mean_revert:
    enabled: true
    tf: "1m"
    ema_len: 50
    z_entry: 2.0
    z_exit: 0.5
    adx_max: 18
    atr_stop_mult: 1.0
    max_spread_bp: 8
    time_exit_bars: 6

# === risk & sizing ===
risk:
  max_drawdown: 0.35
  stop_loss_pct: 0.01
  take_profit_pct: 0.1

# === fees ===
fees:
  kraken:
    taker_bp: 26    # example 0.26%
    maker_bp: 16    # example 0.16%

# === features ===
features:
  ml: false
  helius: false
  pump_monitor: false
  telegram: true

# === telemetry / metrics ===
telemetry:
  batch_summary_secs: 60

timeframes: ['1m','5m']

warmup_candles:
  '1m': 1000
  '5m': 600

backfill_days:
  '1m': 2
  '5m': 3
