mode: paper

trading:
  min_score: 0.20
  min_confidence: 0.30
  consensus: weighted
  require_sentiment: false   # CT_REQUIRE_SENTIMENT=false also disables checks
voting_enabled: false  # set true to enable strategy voting
# Example voting configuration
voting_strategies:
  strategies: []
  min_agreeing_votes: 1
exchange:
  name: kraken
  max_concurrency: 3
  request_timeout_ms: 10000

kraken:
  http_pool_size: 50
timeframes: ["1h", "4h", "1d"]
ohlcv:
  storage_path: crypto_bot/data/ohlcv   # directory for persisted OHLCV data
  tail_overlap_bars: 3                  # overlap bars to avoid gaps when appending
  max_bootstrap_bars: 1000              # limit initial bootstrap to this many bars
  progress_logging: false               # include percent/ETA when data is missing
  bootstrap_timeframes: ["1m", "5m", "15m", "1h"]
  defer_timeframes: ["4h", "1d"]
  warmup_candles:
    "1m": 300
    "5m": 300
    "15m": 300
    "1h": 200
    "1d": 100
  initial_history_candles: 600
  scan_lookback_limit: 1200
filters:
  min_ticker_volume: 10000
features:
  ml: false
  helius: false
  pump_monitor: false
  telegram: false

solana_rpc: https://api.mainnet-beta.solana.com  # Custom endpoint
yamlmeme_sniper:
  min_pump_prob: 0.6  # Assessment threshold
  max_dev_hold_pct: 20
  min_liquidity_usd: 5000
  twitter_sentiment_min: 70
  helius_api_key: your_key_here  # For metadata

ohlcv_chunk_size: 20

# === volatility filter ===
volatility_filter:
  max_funding_rate: 0.3
  min_atr_pct: 0.0001

# === sentiment filter ===
sentiment_filter:
  require_sentiment: false   # CT_REQUIRE_SENTIMENT=false skips vetoes regardless
  min_fng: 20
  min_sentiment: 40
