mode: paper

trading:
  min_score: 0.20
  min_confidence: 0.30
  consensus: weighted
  require_sentiment: false
exchange:
  name: kraken
  max_concurrency: 3
  request_timeout_ms: 10000
timeframes: ["1h", "4h", "1d"]
ohlcv:
  bootstrap_timeframes: ['1h']
  defer_timeframes: ['4h', '1d']
filters:
  min_ticker_volume: 10000
features:
  ml: false
  helius: false
  pump_monitor: false
  telegram: false

ohlcv:
  storage_path: crypto_bot/data/ohlcv   # directory for persisted OHLCV data
  tail_overlap_bars: 3                  # overlap bars to avoid gaps when appending
  max_bootstrap_bars: 1000              # limit initial bootstrap to this many bars

solana_rpc: https://api.mainnet-beta.solana.com  # Custom endpoint
yamlmeme_sniper:
  min_pump_prob: 0.6  # Assessment threshold
  max_dev_hold_pct: 20
  min_liquidity_usd: 5000
  twitter_sentiment_min: 70
  helius_api_key: your_key_here  # For metadata

ohlcv_chunk_size: 20

# === volatility filter ===
volatility_filter:
  max_funding_rate: 0.3
  min_atr_pct: 0.0001
