# Helper constants used across crypto_bot utilities

# Known non-Solana base tickers that may be misclassified as mint addresses
NON_SOLANA_BASES = {
    "ADA",
    "BNB",
    "AVAX",
    "APE",
    "BCH",
    "ALGO",
    "ATOM",
    "CRO",
    "DOT",
    "ETH",
    "LINK",
    "LTC",
    "MANA",
    "SHIB",
    "TON",
    "BTC",
    "DOGE",
    "XRP",
    "S",
    "XMR",
    "XTZ",
    "EURR",
    "RLUSD",
    "USDG",
    "USDQ",
    "USTC",
}
